SET foreign_key_checks = 0;
truncate table ProjektyPWR.grupy_zajeciowe;
truncate table ProjektyPWR.grupy_projektowe;
truncate table ProjektyPWR.kursy;
truncate table ProjektyPWR.studenci;
truncate table ProjektyPWR.kursy;
truncate table ProjektyPWR.studenci_do_grup_zajeciowych;
truncate table ProjektyPWR.studenci_do_grup_projektowych;
truncate table ProjektyPWR.Spotkania;
truncate table ProjektyPWR.oceny_czastkowe;
truncate table ProjektyPWR.obecnosc;
SET foreign_key_checks = 1;